services:
  redis:
    container_name: django_ping_redis
    image: redis
  celery:
    container_name: django_ping_celery
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ['celery', '-A', 'django_ping', 'worker', '-l', 'INFO', '-P', 'gevent']
    volumes:
      - .:/home/app/django_ping
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    depends_on:
      - redis
  app:
    container_name: django_ping_webserver
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    volumes:
      - .:/home/app/django_ping
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_HOST=redis
    ports:
      - 8000:8000
    depends_on:
      - redis
      - celery
